[theme]
primaryColor = "#00F5D4"
backgroundColor = "#0A1329"
secondaryBackgroundColor = "#1A2339"
textColor = "#F1F5F9"
font = "sans serif"

[ui]
hideSidebarNav = true

[client]
showSidebarNavigation = false
