[theme]
primaryColor = "#4F7C82"
backgroundColor = "#0A1628"
secondaryBackgroundColor = "#0e3a40"
textColor = "#B8E3E9"
font = "sans serif"

[ui]
hideSidebarNav = true

[client]
showSidebarNavigation = false
